export const usa_states:  { code: string , state_name: string}[] = [
  { code: "AL", state_name: "Alabama" },
  { code: "AK", state_name: "Alaska" },
  { code: "AZ", state_name: "Arizona" },
  { code: "AR", state_name: "Arkansas" },
  { code: "CA", state_name: "California" },
  { code: "CO", state_name: "Colorado" },
  { code: "CT", state_name: "Connecticut" },
  { code: "DE", state_name: "Delaware" },
  { code: "FL", state_name: "Florida" },
  { code: "GA", state_name: "Georgia" },
  { code: "HI", state_name: "Hawaii" },
  { code: "ID", state_name: "Idaho" },
  { code: "IL", state_name: "Illinois" },
  { code: "IN", state_name: "Indiana" },
  { code: "IA", state_name: "Iowa" },
  { code: "KS", state_name: "Kansas" },
  { code: "KY", state_name: "Kentucky" },
  { code: "LA", state_name: "Louisiana" },
  { code: "ME", state_name: "Maine" },
  { code: "MD", state_name: "Maryland" },
  { code: "MA", state_name: "Massachusetts" },
  { code: "MI", state_name: "Michigan" },
  { code: "MN", state_name: "Minnesota" },
  { code: "MO", state_name: "Missouri" },
  { code: "MT", state_name: "Montana" },
  { code: "NE", state_name: "Nebraska" },
  { code: "NV", state_name: "Nevada" },
  { code: "NH", state_name: "New Hampshire" },
  { code: "NJ", state_name: "New Jersey" },
  { code: "NM", state_name: "New Mexico" },
  { code: "NY", state_name: "New York" },
  { code: "NC", state_name: "North Carolina" },
  { code: "ND", state_name: "North Dakota" },
  { code: "OH", state_name: "Ohio" },
  { code: "OK", state_name: "Oklahoma" },
  { code: "OR", state_name: "Oregon" },
  { code: "PA", state_name: "Pennsylvania" },
  { code: "RI", state_name: "Rhode Island" },
  { code: "SC", state_name: "South Carolina" },
  { code: "SD", state_name: "South Dakota" },
  { code: "TN", state_name: "Tennessee" },
  { code: "TX", state_name: "Texas" },
  { code: "UT", state_name: "Utah" },
  { code: "VT", state_name: "Vermont" },
  { code: "VA", state_name: "Virginia" },
  { code: "WA", state_name: "Washington" },
  { code: "WV", state_name: "West Virginia" },
  { code: "WI", state_name: "Wisconsin" },
  { code: "WY", state_name: "Wyoming" }
];


